### ISSUE TITLE
Early-access list management

### ISSUE THREAD

**Issue by PeeHaa** [dependenci/roadmap#8]

**Comment by m1guelpf** [comment]
@PeeHaa KickOffLabs is used to manage the beta access, also:
> We don’t share your personally identifying information, or data you collect through Your Sites, with anyone, except as needed, to provide product support, to comply with the law, or to protect Our rights.

They don't use your email (as stated in their privacy policy), only store it so I can manage beta access, and deleted once you get your invite.

**Comment by PeeHaa** [comment]
Can you delete it now instead?

**Comment by m1guelpf** [comment]
@PeeHaa Do you want me to send you an invite (and it auto-deletes the info) or to delete you from the list completely?

**Comment by PeeHaa** [comment]
Whatever is easier for you

**Comment by m1guelpf** [comment]
@PeeHaa Sent you an invite, hope you enjoy ComposerCI :smile:
